Update exhaustive_feature_selector.py (#1104)
* Update exhaustive_feature_selector.py 

AttributeError: `np.NINF` was removed in the NumPy 2.0 release. Use `-np.inf` instead.
Fixed this Error.

* Update mlxtend/feature_selection/exhaustive_feature_selector.py

Co-authored-by: Peter Gedeck <gedeck@collaborativedrug.com>

---------

Co-authored-by: Sebastian Raschka <mail@sebastianraschka.com>
Co-authored-by: Peter Gedeck <gedeck@collaborativedrug.com>